// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ribproto/openconfig/enums/enums.proto

package openconfig_enums

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/aristanetworks/ygot/proto/yext"
import _ "github.com/aristanetworks/ygot/proto/ywrapper"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// OpenconfigBgpTypesAFISAFITYPE represents an enumerated type generated for the YANG identity AFI_SAFI_TYPE.
type OpenconfigBgpTypesAFISAFITYPE int32

const (
	OpenconfigBgpTypesAFISAFITYPE_OPENCONFIGBGPTYPESAFISAFITYPE_UNSET                OpenconfigBgpTypesAFISAFITYPE = 0
	OpenconfigBgpTypesAFISAFITYPE_OPENCONFIGBGPTYPESAFISAFITYPE_L3VPN_IPV4_MULTICAST OpenconfigBgpTypesAFISAFITYPE = 53601692
	OpenconfigBgpTypesAFISAFITYPE_OPENCONFIGBGPTYPESAFISAFITYPE_L3VPN_IPV6_MULTICAST OpenconfigBgpTypesAFISAFITYPE = 171618750
	OpenconfigBgpTypesAFISAFITYPE_OPENCONFIGBGPTYPESAFISAFITYPE_IPV4_UNICAST         OpenconfigBgpTypesAFISAFITYPE = 196909421
	OpenconfigBgpTypesAFISAFITYPE_OPENCONFIGBGPTYPESAFISAFITYPE_L2VPN_EVPN           OpenconfigBgpTypesAFISAFITYPE = 213517208
	OpenconfigBgpTypesAFISAFITYPE_OPENCONFIGBGPTYPESAFISAFITYPE_IPV6_UNICAST         OpenconfigBgpTypesAFISAFITYPE = 270342995
	OpenconfigBgpTypesAFISAFITYPE_OPENCONFIGBGPTYPESAFISAFITYPE_IPV4_LABELED_UNICAST OpenconfigBgpTypesAFISAFITYPE = 279108253
	OpenconfigBgpTypesAFISAFITYPE_OPENCONFIGBGPTYPESAFISAFITYPE_L3VPN_IPV4_UNICAST   OpenconfigBgpTypesAFISAFITYPE = 358537365
	OpenconfigBgpTypesAFISAFITYPE_OPENCONFIGBGPTYPESAFISAFITYPE_IPV6_LABELED_UNICAST OpenconfigBgpTypesAFISAFITYPE = 420698035
	OpenconfigBgpTypesAFISAFITYPE_OPENCONFIGBGPTYPESAFISAFITYPE_L3VPN_IPV6_UNICAST   OpenconfigBgpTypesAFISAFITYPE = 421890363
	OpenconfigBgpTypesAFISAFITYPE_OPENCONFIGBGPTYPESAFISAFITYPE_L2VPN_VPLS           OpenconfigBgpTypesAFISAFITYPE = 533405094
)

var OpenconfigBgpTypesAFISAFITYPE_name = map[int32]string{
	0:         "OPENCONFIGBGPTYPESAFISAFITYPE_UNSET",
	53601692:  "OPENCONFIGBGPTYPESAFISAFITYPE_L3VPN_IPV4_MULTICAST",
	171618750: "OPENCONFIGBGPTYPESAFISAFITYPE_L3VPN_IPV6_MULTICAST",
	196909421: "OPENCONFIGBGPTYPESAFISAFITYPE_IPV4_UNICAST",
	213517208: "OPENCONFIGBGPTYPESAFISAFITYPE_L2VPN_EVPN",
	270342995: "OPENCONFIGBGPTYPESAFISAFITYPE_IPV6_UNICAST",
	279108253: "OPENCONFIGBGPTYPESAFISAFITYPE_IPV4_LABELED_UNICAST",
	358537365: "OPENCONFIGBGPTYPESAFISAFITYPE_L3VPN_IPV4_UNICAST",
	420698035: "OPENCONFIGBGPTYPESAFISAFITYPE_IPV6_LABELED_UNICAST",
	421890363: "OPENCONFIGBGPTYPESAFISAFITYPE_L3VPN_IPV6_UNICAST",
	533405094: "OPENCONFIGBGPTYPESAFISAFITYPE_L2VPN_VPLS",
}
var OpenconfigBgpTypesAFISAFITYPE_value = map[string]int32{
	"OPENCONFIGBGPTYPESAFISAFITYPE_UNSET":                0,
	"OPENCONFIGBGPTYPESAFISAFITYPE_L3VPN_IPV4_MULTICAST": 53601692,
	"OPENCONFIGBGPTYPESAFISAFITYPE_L3VPN_IPV6_MULTICAST": 171618750,
	"OPENCONFIGBGPTYPESAFISAFITYPE_IPV4_UNICAST":         196909421,
	"OPENCONFIGBGPTYPESAFISAFITYPE_L2VPN_EVPN":           213517208,
	"OPENCONFIGBGPTYPESAFISAFITYPE_IPV6_UNICAST":         270342995,
	"OPENCONFIGBGPTYPESAFISAFITYPE_IPV4_LABELED_UNICAST": 279108253,
	"OPENCONFIGBGPTYPESAFISAFITYPE_L3VPN_IPV4_UNICAST":   358537365,
	"OPENCONFIGBGPTYPESAFISAFITYPE_IPV6_LABELED_UNICAST": 420698035,
	"OPENCONFIGBGPTYPESAFISAFITYPE_L3VPN_IPV6_UNICAST":   421890363,
	"OPENCONFIGBGPTYPESAFISAFITYPE_L2VPN_VPLS":           533405094,
}

func (x OpenconfigBgpTypesAFISAFITYPE) String() string {
	return proto.EnumName(OpenconfigBgpTypesAFISAFITYPE_name, int32(x))
}
func (OpenconfigBgpTypesAFISAFITYPE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_enums_5d772372a9d0d554, []int{0}
}

// OpenconfigBgpTypesBGPWELLKNOWNSTDCOMMUNITY represents an enumerated type generated for the YANG identity BGP_WELL_KNOWN_STD_COMMUNITY.
type OpenconfigBgpTypesBGPWELLKNOWNSTDCOMMUNITY int32

const (
	OpenconfigBgpTypesBGPWELLKNOWNSTDCOMMUNITY_OPENCONFIGBGPTYPESBGPWELLKNOWNSTDCOMMUNITY_UNSET               OpenconfigBgpTypesBGPWELLKNOWNSTDCOMMUNITY = 0
	OpenconfigBgpTypesBGPWELLKNOWNSTDCOMMUNITY_OPENCONFIGBGPTYPESBGPWELLKNOWNSTDCOMMUNITY_NO_EXPORT           OpenconfigBgpTypesBGPWELLKNOWNSTDCOMMUNITY = 7425995
	OpenconfigBgpTypesBGPWELLKNOWNSTDCOMMUNITY_OPENCONFIGBGPTYPESBGPWELLKNOWNSTDCOMMUNITY_NO_EXPORT_SUBCONFED OpenconfigBgpTypesBGPWELLKNOWNSTDCOMMUNITY = 75227749
	OpenconfigBgpTypesBGPWELLKNOWNSTDCOMMUNITY_OPENCONFIGBGPTYPESBGPWELLKNOWNSTDCOMMUNITY_NOPEER              OpenconfigBgpTypesBGPWELLKNOWNSTDCOMMUNITY = 77476850
	OpenconfigBgpTypesBGPWELLKNOWNSTDCOMMUNITY_OPENCONFIGBGPTYPESBGPWELLKNOWNSTDCOMMUNITY_NO_ADVERTISE        OpenconfigBgpTypesBGPWELLKNOWNSTDCOMMUNITY = 126797620
)

var OpenconfigBgpTypesBGPWELLKNOWNSTDCOMMUNITY_name = map[int32]string{
	0:         "OPENCONFIGBGPTYPESBGPWELLKNOWNSTDCOMMUNITY_UNSET",
	7425995:   "OPENCONFIGBGPTYPESBGPWELLKNOWNSTDCOMMUNITY_NO_EXPORT",
	75227749:  "OPENCONFIGBGPTYPESBGPWELLKNOWNSTDCOMMUNITY_NO_EXPORT_SUBCONFED",
	77476850:  "OPENCONFIGBGPTYPESBGPWELLKNOWNSTDCOMMUNITY_NOPEER",
	126797620: "OPENCONFIGBGPTYPESBGPWELLKNOWNSTDCOMMUNITY_NO_ADVERTISE",
}
var OpenconfigBgpTypesBGPWELLKNOWNSTDCOMMUNITY_value = map[string]int32{
	"OPENCONFIGBGPTYPESBGPWELLKNOWNSTDCOMMUNITY_UNSET":               0,
	"OPENCONFIGBGPTYPESBGPWELLKNOWNSTDCOMMUNITY_NO_EXPORT":           7425995,
	"OPENCONFIGBGPTYPESBGPWELLKNOWNSTDCOMMUNITY_NO_EXPORT_SUBCONFED": 75227749,
	"OPENCONFIGBGPTYPESBGPWELLKNOWNSTDCOMMUNITY_NOPEER":              77476850,
	"OPENCONFIGBGPTYPESBGPWELLKNOWNSTDCOMMUNITY_NO_ADVERTISE":        126797620,
}

func (x OpenconfigBgpTypesBGPWELLKNOWNSTDCOMMUNITY) String() string {
	return proto.EnumName(OpenconfigBgpTypesBGPWELLKNOWNSTDCOMMUNITY_name, int32(x))
}
func (OpenconfigBgpTypesBGPWELLKNOWNSTDCOMMUNITY) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_enums_5d772372a9d0d554, []int{1}
}

// OpenconfigPolicyTypesINSTALLPROTOCOLTYPE represents an enumerated type generated for the YANG identity INSTALL_PROTOCOL_TYPE.
type OpenconfigPolicyTypesINSTALLPROTOCOLTYPE int32

const (
	OpenconfigPolicyTypesINSTALLPROTOCOLTYPE_OPENCONFIGPOLICYTYPESINSTALLPROTOCOLTYPE_UNSET              OpenconfigPolicyTypesINSTALLPROTOCOLTYPE = 0
	OpenconfigPolicyTypesINSTALLPROTOCOLTYPE_OPENCONFIGPOLICYTYPESINSTALLPROTOCOLTYPE_STATIC             OpenconfigPolicyTypesINSTALLPROTOCOLTYPE = 164198026
	OpenconfigPolicyTypesINSTALLPROTOCOLTYPE_OPENCONFIGPOLICYTYPESINSTALLPROTOCOLTYPE_LOCAL_AGGREGATE    OpenconfigPolicyTypesINSTALLPROTOCOLTYPE = 167243989
	OpenconfigPolicyTypesINSTALLPROTOCOLTYPE_OPENCONFIGPOLICYTYPESINSTALLPROTOCOLTYPE_OSPF               OpenconfigPolicyTypesINSTALLPROTOCOLTYPE = 187006448
	OpenconfigPolicyTypesINSTALLPROTOCOLTYPE_OPENCONFIGPOLICYTYPESINSTALLPROTOCOLTYPE_ISIS               OpenconfigPolicyTypesINSTALLPROTOCOLTYPE = 308545656
	OpenconfigPolicyTypesINSTALLPROTOCOLTYPE_OPENCONFIGPOLICYTYPESINSTALLPROTOCOLTYPE_BGP                OpenconfigPolicyTypesINSTALLPROTOCOLTYPE = 436650411
	OpenconfigPolicyTypesINSTALLPROTOCOLTYPE_OPENCONFIGPOLICYTYPESINSTALLPROTOCOLTYPE_DIRECTLY_CONNECTED OpenconfigPolicyTypesINSTALLPROTOCOLTYPE = 463126862
	OpenconfigPolicyTypesINSTALLPROTOCOLTYPE_OPENCONFIGPOLICYTYPESINSTALLPROTOCOLTYPE_OSPF3              OpenconfigPolicyTypesINSTALLPROTOCOLTYPE = 470106339
)

var OpenconfigPolicyTypesINSTALLPROTOCOLTYPE_name = map[int32]string{
	0:         "OPENCONFIGPOLICYTYPESINSTALLPROTOCOLTYPE_UNSET",
	164198026: "OPENCONFIGPOLICYTYPESINSTALLPROTOCOLTYPE_STATIC",
	167243989: "OPENCONFIGPOLICYTYPESINSTALLPROTOCOLTYPE_LOCAL_AGGREGATE",
	187006448: "OPENCONFIGPOLICYTYPESINSTALLPROTOCOLTYPE_OSPF",
	308545656: "OPENCONFIGPOLICYTYPESINSTALLPROTOCOLTYPE_ISIS",
	436650411: "OPENCONFIGPOLICYTYPESINSTALLPROTOCOLTYPE_BGP",
	463126862: "OPENCONFIGPOLICYTYPESINSTALLPROTOCOLTYPE_DIRECTLY_CONNECTED",
	470106339: "OPENCONFIGPOLICYTYPESINSTALLPROTOCOLTYPE_OSPF3",
}
var OpenconfigPolicyTypesINSTALLPROTOCOLTYPE_value = map[string]int32{
	"OPENCONFIGPOLICYTYPESINSTALLPROTOCOLTYPE_UNSET":              0,
	"OPENCONFIGPOLICYTYPESINSTALLPROTOCOLTYPE_STATIC":             164198026,
	"OPENCONFIGPOLICYTYPESINSTALLPROTOCOLTYPE_LOCAL_AGGREGATE":    167243989,
	"OPENCONFIGPOLICYTYPESINSTALLPROTOCOLTYPE_OSPF":               187006448,
	"OPENCONFIGPOLICYTYPESINSTALLPROTOCOLTYPE_ISIS":               308545656,
	"OPENCONFIGPOLICYTYPESINSTALLPROTOCOLTYPE_BGP":                436650411,
	"OPENCONFIGPOLICYTYPESINSTALLPROTOCOLTYPE_DIRECTLY_CONNECTED": 463126862,
	"OPENCONFIGPOLICYTYPESINSTALLPROTOCOLTYPE_OSPF3":              470106339,
}

func (x OpenconfigPolicyTypesINSTALLPROTOCOLTYPE) String() string {
	return proto.EnumName(OpenconfigPolicyTypesINSTALLPROTOCOLTYPE_name, int32(x))
}
func (OpenconfigPolicyTypesINSTALLPROTOCOLTYPE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_enums_5d772372a9d0d554, []int{2}
}

// OpenconfigRibBgpAsPathSegmentType represents an enumerated type generated for the YANG enumerated type as-path-segment-type.
type OpenconfigRibBgpAsPathSegmentType int32

const (
	OpenconfigRibBgpAsPathSegmentType_OPENCONFIGRIBBGPASPATHSEGMENTTYPE_UNSET              OpenconfigRibBgpAsPathSegmentType = 0
	OpenconfigRibBgpAsPathSegmentType_OPENCONFIGRIBBGPASPATHSEGMENTTYPE_AS_SEQ             OpenconfigRibBgpAsPathSegmentType = 1
	OpenconfigRibBgpAsPathSegmentType_OPENCONFIGRIBBGPASPATHSEGMENTTYPE_AS_SET             OpenconfigRibBgpAsPathSegmentType = 2
	OpenconfigRibBgpAsPathSegmentType_OPENCONFIGRIBBGPASPATHSEGMENTTYPE_AS_CONFED_SEQUENCE OpenconfigRibBgpAsPathSegmentType = 3
	OpenconfigRibBgpAsPathSegmentType_OPENCONFIGRIBBGPASPATHSEGMENTTYPE_AS_CONFED_SET      OpenconfigRibBgpAsPathSegmentType = 4
)

var OpenconfigRibBgpAsPathSegmentType_name = map[int32]string{
	0: "OPENCONFIGRIBBGPASPATHSEGMENTTYPE_UNSET",
	1: "OPENCONFIGRIBBGPASPATHSEGMENTTYPE_AS_SEQ",
	2: "OPENCONFIGRIBBGPASPATHSEGMENTTYPE_AS_SET",
	3: "OPENCONFIGRIBBGPASPATHSEGMENTTYPE_AS_CONFED_SEQUENCE",
	4: "OPENCONFIGRIBBGPASPATHSEGMENTTYPE_AS_CONFED_SET",
}
var OpenconfigRibBgpAsPathSegmentType_value = map[string]int32{
	"OPENCONFIGRIBBGPASPATHSEGMENTTYPE_UNSET":              0,
	"OPENCONFIGRIBBGPASPATHSEGMENTTYPE_AS_SEQ":             1,
	"OPENCONFIGRIBBGPASPATHSEGMENTTYPE_AS_SET":             2,
	"OPENCONFIGRIBBGPASPATHSEGMENTTYPE_AS_CONFED_SEQUENCE": 3,
	"OPENCONFIGRIBBGPASPATHSEGMENTTYPE_AS_CONFED_SET":      4,
}

func (x OpenconfigRibBgpAsPathSegmentType) String() string {
	return proto.EnumName(OpenconfigRibBgpAsPathSegmentType_name, int32(x))
}
func (OpenconfigRibBgpAsPathSegmentType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_enums_5d772372a9d0d554, []int{3}
}

// OpenconfigRibBgpBgpOriginAttrType represents an enumerated type generated for the YANG enumerated type bgp-origin-attr-type.
type OpenconfigRibBgpBgpOriginAttrType int32

const (
	OpenconfigRibBgpBgpOriginAttrType_OPENCONFIGRIBBGPBGPORIGINATTRTYPE_UNSET      OpenconfigRibBgpBgpOriginAttrType = 0
	OpenconfigRibBgpBgpOriginAttrType_OPENCONFIGRIBBGPBGPORIGINATTRTYPE_IGP        OpenconfigRibBgpBgpOriginAttrType = 1
	OpenconfigRibBgpBgpOriginAttrType_OPENCONFIGRIBBGPBGPORIGINATTRTYPE_EGP        OpenconfigRibBgpBgpOriginAttrType = 2
	OpenconfigRibBgpBgpOriginAttrType_OPENCONFIGRIBBGPBGPORIGINATTRTYPE_INCOMPLETE OpenconfigRibBgpBgpOriginAttrType = 3
)

var OpenconfigRibBgpBgpOriginAttrType_name = map[int32]string{
	0: "OPENCONFIGRIBBGPBGPORIGINATTRTYPE_UNSET",
	1: "OPENCONFIGRIBBGPBGPORIGINATTRTYPE_IGP",
	2: "OPENCONFIGRIBBGPBGPORIGINATTRTYPE_EGP",
	3: "OPENCONFIGRIBBGPBGPORIGINATTRTYPE_INCOMPLETE",
}
var OpenconfigRibBgpBgpOriginAttrType_value = map[string]int32{
	"OPENCONFIGRIBBGPBGPORIGINATTRTYPE_UNSET":      0,
	"OPENCONFIGRIBBGPBGPORIGINATTRTYPE_IGP":        1,
	"OPENCONFIGRIBBGPBGPORIGINATTRTYPE_EGP":        2,
	"OPENCONFIGRIBBGPBGPORIGINATTRTYPE_INCOMPLETE": 3,
}

func (x OpenconfigRibBgpBgpOriginAttrType) String() string {
	return proto.EnumName(OpenconfigRibBgpBgpOriginAttrType_name, int32(x))
}
func (OpenconfigRibBgpBgpOriginAttrType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_enums_5d772372a9d0d554, []int{4}
}

// OpenconfigRibBgpTypesINVALIDROUTEREASON represents an enumerated type generated for the YANG identity INVALID_ROUTE_REASON.
type OpenconfigRibBgpTypesINVALIDROUTEREASON int32

const (
	OpenconfigRibBgpTypesINVALIDROUTEREASON_OPENCONFIGRIBBGPTYPESINVALIDROUTEREASON_UNSET                OpenconfigRibBgpTypesINVALIDROUTEREASON = 0
	OpenconfigRibBgpTypesINVALIDROUTEREASON_OPENCONFIGRIBBGPTYPESINVALIDROUTEREASON_INVALID_AS_LOOP      OpenconfigRibBgpTypesINVALIDROUTEREASON = 281940072
	OpenconfigRibBgpTypesINVALIDROUTEREASON_OPENCONFIGRIBBGPTYPESINVALIDROUTEREASON_INVALID_ORIGINATOR   OpenconfigRibBgpTypesINVALIDROUTEREASON = 329543457
	OpenconfigRibBgpTypesINVALIDROUTEREASON_OPENCONFIGRIBBGPTYPESINVALIDROUTEREASON_INVALID_CLUSTER_LOOP OpenconfigRibBgpTypesINVALIDROUTEREASON = 363552896
	OpenconfigRibBgpTypesINVALIDROUTEREASON_OPENCONFIGRIBBGPTYPESINVALIDROUTEREASON_INVALID_CONFED       OpenconfigRibBgpTypesINVALIDROUTEREASON = 404003798
)

var OpenconfigRibBgpTypesINVALIDROUTEREASON_name = map[int32]string{
	0:         "OPENCONFIGRIBBGPTYPESINVALIDROUTEREASON_UNSET",
	281940072: "OPENCONFIGRIBBGPTYPESINVALIDROUTEREASON_INVALID_AS_LOOP",
	329543457: "OPENCONFIGRIBBGPTYPESINVALIDROUTEREASON_INVALID_ORIGINATOR",
	363552896: "OPENCONFIGRIBBGPTYPESINVALIDROUTEREASON_INVALID_CLUSTER_LOOP",
	404003798: "OPENCONFIGRIBBGPTYPESINVALIDROUTEREASON_INVALID_CONFED",
}
var OpenconfigRibBgpTypesINVALIDROUTEREASON_value = map[string]int32{
	"OPENCONFIGRIBBGPTYPESINVALIDROUTEREASON_UNSET":                0,
	"OPENCONFIGRIBBGPTYPESINVALIDROUTEREASON_INVALID_AS_LOOP":      281940072,
	"OPENCONFIGRIBBGPTYPESINVALIDROUTEREASON_INVALID_ORIGINATOR":   329543457,
	"OPENCONFIGRIBBGPTYPESINVALIDROUTEREASON_INVALID_CLUSTER_LOOP": 363552896,
	"OPENCONFIGRIBBGPTYPESINVALIDROUTEREASON_INVALID_CONFED":       404003798,
}

func (x OpenconfigRibBgpTypesINVALIDROUTEREASON) String() string {
	return proto.EnumName(OpenconfigRibBgpTypesINVALIDROUTEREASON_name, int32(x))
}
func (OpenconfigRibBgpTypesINVALIDROUTEREASON) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_enums_5d772372a9d0d554, []int{5}
}

func init() {
	proto.RegisterEnum("openconfig.enums.OpenconfigBgpTypesAFISAFITYPE", OpenconfigBgpTypesAFISAFITYPE_name, OpenconfigBgpTypesAFISAFITYPE_value)
	proto.RegisterEnum("openconfig.enums.OpenconfigBgpTypesBGPWELLKNOWNSTDCOMMUNITY", OpenconfigBgpTypesBGPWELLKNOWNSTDCOMMUNITY_name, OpenconfigBgpTypesBGPWELLKNOWNSTDCOMMUNITY_value)
	proto.RegisterEnum("openconfig.enums.OpenconfigPolicyTypesINSTALLPROTOCOLTYPE", OpenconfigPolicyTypesINSTALLPROTOCOLTYPE_name, OpenconfigPolicyTypesINSTALLPROTOCOLTYPE_value)
	proto.RegisterEnum("openconfig.enums.OpenconfigRibBgpAsPathSegmentType", OpenconfigRibBgpAsPathSegmentType_name, OpenconfigRibBgpAsPathSegmentType_value)
	proto.RegisterEnum("openconfig.enums.OpenconfigRibBgpBgpOriginAttrType", OpenconfigRibBgpBgpOriginAttrType_name, OpenconfigRibBgpBgpOriginAttrType_value)
	proto.RegisterEnum("openconfig.enums.OpenconfigRibBgpTypesINVALIDROUTEREASON", OpenconfigRibBgpTypesINVALIDROUTEREASON_name, OpenconfigRibBgpTypesINVALIDROUTEREASON_value)
}

func init() {
	proto.RegisterFile("ribproto/openconfig/enums/enums.proto", fileDescriptor_enums_5d772372a9d0d554)
}

var fileDescriptor_enums_5d772372a9d0d554 = []byte{
	// 1058 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0x7b, 0x68, 0x1c, 0xc5,
	0x1f, 0xff, 0x6d, 0x92, 0x5f, 0xb4, 0x43, 0x6b, 0xc7, 0xf1, 0x85, 0x0b, 0xfe, 0x21, 0xb5, 0xa4,
	0x9c, 0x9a, 0x33, 0x0f, 0x52, 0xd1, 0x98, 0x3a, 0xbb, 0x37, 0x59, 0x07, 0x37, 0x3b, 0x93, 0x9d,
	0xb9, 0xab, 0x27, 0x84, 0x23, 0x09, 0xe7, 0xf5, 0xd0, 0xdc, 0x1d, 0x77, 0x5b, 0x6a, 0xfe, 0xab,
	0x2b, 0x2a, 0x28, 0x48, 0x55, 0x22, 0x82, 0x16, 0x1f, 0xa0, 0x7f, 0xa8, 0x45, 0x7c, 0x0b, 0x81,
	0xa2, 0xe0, 0x93, 0xa2, 0xf8, 0x40, 0xff, 0x10, 0xf1, 0x41, 0x11, 0x8b, 0x52, 0x94, 0x22, 0x58,
	0x28, 0x88, 0xec, 0x6e, 0xb2, 0xbb, 0xf7, 0x48, 0xb2, 0xab, 0xff, 0x1c, 0x37, 0xdf, 0xcf, 0x7c,
	0x3e, 0xf3, 0xd9, 0xef, 0x63, 0x76, 0xc1, 0xee, 0x66, 0x75, 0xa1, 0xd1, 0xac, 0x3b, 0xf5, 0x6c,
	0xbd, 0x51, 0xae, 0x2d, 0xd6, 0x6b, 0x77, 0x54, 0x2b, 0xd9, 0x72, 0xed, 0xe0, 0x52, 0x2b, 0xf8,
	0x1d, 0xf6, 0x41, 0x04, 0x23, 0x74, 0xd8, 0x8f, 0xab, 0x93, 0x95, 0xaa, 0x73, 0xe0, 0xe0, 0xc2,
	0xf0, 0x62, 0x7d, 0x29, 0x3b, 0xdf, 0xac, 0xb6, 0x9c, 0xf9, 0x5a, 0xd9, 0x39, 0x54, 0x6f, 0xde,
	0xd9, 0xca, 0x2e, 0x57, 0xea, 0x4e, 0x36, 0x10, 0x5d, 0x3e, 0xd4, 0x9c, 0x6f, 0x34, 0xca, 0xcd,
	0xf0, 0x4f, 0xa0, 0xa7, 0x8e, 0x27, 0x63, 0x97, 0xef, 0x76, 0xfc, 0x9f, 0x80, 0x95, 0xf9, 0x70,
	0x10, 0x5c, 0xc1, 0x42, 0x23, 0x5a, 0xa5, 0x21, 0x97, 0x1b, 0xe5, 0x16, 0x9e, 0xa6, 0x02, 0x4f,
	0x53, 0x59, 0xe4, 0x04, 0x0d, 0x81, 0x5d, 0x8c, 0x13, 0x4b, 0x67, 0xd6, 0x34, 0x35, 0x34, 0x83,
	0x7b, 0x41, 0x11, 0xdb, 0x50, 0xca, 0x5b, 0x82, 0x48, 0xf8, 0x3f, 0x64, 0x83, 0xd1, 0xcd, 0x37,
	0x9a, 0x63, 0x05, 0x6e, 0x95, 0x28, 0x2f, 0x8c, 0x97, 0x66, 0xf2, 0xa6, 0xa4, 0x3a, 0x16, 0x12,
	0x3e, 0x75, 0xe2, 0xa3, 0xcb, 0xd5, 0xcb, 0x5c, 0x7c, 0x71, 0x2f, 0x34, 0x85, 0xe6, 0x44, 0x4c,
	0xf3, 0xf8, 0xc9, 0x5f, 0x67, 0xdb, 0x35, 0x63, 0x28, 0xd2, 0x40, 0x66, 0x73, 0x4d, 0xdf, 0x43,
	0xde, 0x0a, 0xb4, 0x4e, 0xbf, 0x76, 0x66, 0x4e, 0xdd, 0xe9, 0xe2, 0xed, 0xf1, 0x28, 0x9a, 0x02,
	0x7b, 0xb6, 0xf0, 0x35, 0xea, 0x9d, 0x4c, 0x0a, 0xdc, 0x82, 0x4f, 0x3c, 0x70, 0xaa, 0xac, 0xee,
	0x70, 0x31, 0x88, 0x62, 0x48, 0x4f, 0xe0, 0x61, 0x22, 0xf4, 0xf0, 0xd5, 0x5b, 0x7f, 0x1e, 0x56,
	0xd6, 0x4d, 0x84, 0x61, 0x24, 0xb6, 0x4a, 0x8e, 0x6f, 0xd9, 0xc4, 0x1a, 0x31, 0x49, 0x2e, 0x14,
	0x3b, 0xfa, 0xe6, 0x43, 0xf7, 0x29, 0x7e, 0x76, 0x7a, 0xc1, 0x88, 0x81, 0xeb, 0x12, 0x57, 0x71,
	0x5d, 0x72, 0xe5, 0xd5, 0x73, 0x2f, 0x2a, 0xea, 0x25, 0x2e, 0x46, 0xdd, 0x60, 0x22, 0x97, 0x13,
	0x5d, 0x2e, 0x5f, 0x7f, 0xe5, 0xd3, 0x8f, 0x43, 0x97, 0x13, 0xff, 0xc1, 0x65, 0x94, 0xc5, 0xd5,
	0x47, 0x1f, 0xff, 0xa4, 0xc3, 0x65, 0x94, 0xcb, 0x7d, 0xc9, 0x0a, 0x5a, 0xe0, 0xa6, 0x80, 0x2f,
	0xac, 0xbe, 0xfc, 0xb7, 0x12, 0xab, 0xa8, 0x17, 0xcc, 0x3c, 0xd7, 0x0f, 0x32, 0xdd, 0x83, 0xa4,
	0x19, 0x7c, 0x3f, 0x31, 0xcd, 0x5b, 0x2d, 0xb6, 0xdf, 0x12, 0x32, 0xa7, 0xb3, 0x99, 0x99, 0xbc,
	0x45, 0x65, 0x11, 0x8d, 0xf7, 0x7a, 0x80, 0x8d, 0x76, 0x87, 0x23, 0x46, 0xc1, 0x78, 0x0a, 0x96,
	0xc5, 0x4a, 0xe4, 0x36, 0xce, 0x6c, 0x09, 0x4f, 0x3c, 0xfd, 0x41, 0xbf, 0xba, 0xdd, 0xc5, 0xdb,
	0xc2, 0x10, 0x9a, 0x03, 0x53, 0xff, 0x46, 0xaa, 0x24, 0xf2, 0x9a, 0xc7, 0x21, 0x39, 0xf8, 0xf3,
	0xfb, 0xbf, 0xef, 0x52, 0x2f, 0x75, 0xf1, 0x45, 0x3d, 0x40, 0xa4, 0x83, 0x91, 0x54, 0xf2, 0x9c,
	0x10, 0x1b, 0x9e, 0xf9, 0xe5, 0xec, 0x55, 0xea, 0x36, 0x17, 0x0f, 0x06, 0x6b, 0xc4, 0xc0, 0xde,
	0x74, 0x1e, 0x71, 0xae, 0x40, 0x6c, 0x49, 0x05, 0x81, 0x6f, 0x3c, 0xbc, 0x3a, 0xe9, 0x4f, 0x4c,
	0x3c, 0x9a, 0xf9, 0x62, 0x00, 0xec, 0x89, 0x8a, 0xc4, 0xeb, 0x77, 0x55, 0x17, 0x97, 0xfd, 0x3a,
	0x51, 0x4b, 0x48, 0x6c, 0x9a, 0xdc, 0x66, 0x92, 0xe9, 0xcc, 0xf4, 0x2f, 0xbe, 0x51, 0x30, 0x1c,
	0x9d, 0xce, 0x99, 0x49, 0xf5, 0xa2, 0x6f, 0xa0, 0xc7, 0xde, 0xb0, 0x40, 0x18, 0x64, 0x13, 0x73,
	0x84, 0xc4, 0x92, 0xea, 0xf0, 0xc1, 0xd3, 0xcf, 0x5b, 0xfe, 0x43, 0x07, 0x6b, 0x24, 0xc0, 0xf5,
	0x89, 0x25, 0x4c, 0xa6, 0x63, 0xb3, 0x84, 0x0d, 0xc3, 0x26, 0x06, 0x96, 0x04, 0x7e, 0xfd, 0xd3,
	0x0f, 0x4c, 0x45, 0x2e, 0xde, 0xd9, 0x01, 0xa0, 0x9b, 0xc0, 0xb5, 0x89, 0x45, 0x99, 0xe0, 0xd3,
	0xf0, 0x8f, 0x73, 0x2b, 0x45, 0xf5, 0x3c, 0x17, 0x0f, 0x78, 0x2b, 0x34, 0x95, 0x82, 0x4e, 0x05,
	0x15, 0xf0, 0xec, 0x91, 0x23, 0x8f, 0x29, 0x3e, 0xdf, 0x5b, 0xa2, 0x49, 0x70, 0x4d, 0x62, 0xbe,
	0x66, 0x70, 0xf8, 0xd2, 0xbd, 0x4f, 0x7e, 0xae, 0xa8, 0x83, 0x2e, 0xee, 0xd7, 0x0c, 0x8e, 0x6e,
	0x07, 0x37, 0x26, 0x66, 0xe7, 0xa8, 0x4d, 0x74, 0x69, 0x16, 0x4b, 0x3a, 0xb3, 0x2c, 0xa2, 0x4b,
	0x92, 0x83, 0x9f, 0xb9, 0xbf, 0x7d, 0x17, 0xcc, 0x7d, 0x37, 0x88, 0x6e, 0x4e, 0x51, 0x64, 0x2f,
	0x15, 0x63, 0xf0, 0xe4, 0x3d, 0x2b, 0x3f, 0x2a, 0xea, 0xf9, 0x2e, 0xfe, 0xbf, 0xbf, 0xce, 0x7c,
	0xdb, 0x07, 0xae, 0x8c, 0x7a, 0xca, 0xae, 0x2e, 0x68, 0x95, 0x06, 0x6e, 0xf1, 0x79, 0xe7, 0x80,
	0x28, 0x57, 0x96, 0xca, 0x35, 0xc7, 0x6b, 0x30, 0x74, 0x35, 0x18, 0x8a, 0xce, 0xb1, 0xa9, 0xa6,
	0x19, 0x1c, 0x0b, 0x8e, 0xe5, 0x2d, 0x82, 0x18, 0x33, 0xc4, 0x92, 0x6d, 0x5d, 0xb4, 0x37, 0x7e,
	0x19, 0x6d, 0xb4, 0x19, 0x8b, 0x92, 0x20, 0xb3, 0x50, 0xf1, 0x7b, 0x27, 0x58, 0xa4, 0x20, 0x4a,
	0xd8, 0x17, 0x11, 0xbd, 0xfb, 0x74, 0x3c, 0x11, 0x31, 0x98, 0x6e, 0xef, 0xac, 0x3c, 0xb1, 0x74,
	0x02, 0xfb, 0xfd, 0xbc, 0x76, 0x03, 0x88, 0xc4, 0x07, 0x21, 0x89, 0xa0, 0x84, 0x03, 0x2a, 0x74,
	0xf1, 0x8e, 0xb6, 0x58, 0xe6, 0x2f, 0xa5, 0x3b, 0xb9, 0x5a, 0xa5, 0xc1, 0x9a, 0xd5, 0x4a, 0xb5,
	0x86, 0x1d, 0xa7, 0xb9, 0x51, 0x72, 0x35, 0x83, 0x33, 0x9b, 0x1a, 0xd4, 0xc2, 0x52, 0xda, 0x6d,
	0xc9, 0x1d, 0x01, 0xbb, 0xb7, 0xde, 0x4c, 0x0d, 0x0e, 0x83, 0x06, 0xa4, 0x06, 0x4f, 0x46, 0x21,
	0x06, 0x87, 0x7d, 0x3e, 0x85, 0x18, 0x1c, 0xed, 0x8b, 0x77, 0xfc, 0x86, 0xa7, 0x58, 0x3a, 0x9b,
	0xe1, 0x26, 0x91, 0x5e, 0x22, 0xbd, 0xf7, 0x49, 0x14, 0xc8, 0x1c, 0xef, 0x07, 0x43, 0x9d, 0x4f,
	0xbe, 0x76, 0x55, 0x15, 0xb0, 0x49, 0x73, 0x36, 0xcb, 0x4b, 0x62, 0x13, 0x2c, 0x98, 0x85, 0x46,
	0xe2, 0xe3, 0x19, 0x1c, 0xb6, 0xd6, 0xc4, 0x9d, 0x5b, 0xc3, 0x2c, 0x88, 0xf8, 0xd5, 0xba, 0x39,
	0x65, 0x2d, 0xe4, 0x55, 0xcb, 0x64, 0x8c, 0xc3, 0x53, 0xcf, 0xbc, 0x73, 0xbf, 0xe2, 0xdf, 0x32,
	0x1d, 0x08, 0x2a, 0x82, 0x1b, 0xd2, 0x8a, 0xae, 0x67, 0x84, 0xd9, 0xf0, 0xd9, 0xef, 0x1f, 0x39,
	0x1a, 0xcc, 0x69, 0x37, 0x88, 0xe6, 0xc0, 0x64, 0x5a, 0x69, 0xdd, 0xcc, 0x0b, 0x49, 0xec, 0xc0,
	0xf4, 0xe1, 0xf7, 0x8e, 0x1d, 0x5b, 0xfb, 0x9e, 0xe8, 0x01, 0xa3, 0x59, 0x30, 0x91, 0x5a, 0x3e,
	0x78, 0x0b, 0x7e, 0xf3, 0xf6, 0x97, 0xef, 0x2a, 0xea, 0x85, 0x2e, 0xbe, 0xa0, 0x1d, 0x58, 0x18,
	0xf4, 0x3f, 0xb0, 0xc7, 0xfe, 0x09, 0x00, 0x00, 0xff, 0xff, 0xe4, 0x12, 0x48, 0xcd, 0x0f, 0x0c,
	0x00, 0x00,
}
